# Core Jekyll Configuration
locale: 'en'
timezone: 'Etc/UTC'
# url: 'https://www.example.com'
permalink: '/articles/:title'
include:
  - _pages
exclude:
  - .git*
  - _site
  - .gitattributes
  - .gitignore
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - LICENSE
  - CNAME

sass:
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

# Progressive Web App Settings
pwa_title             : 'Groveld'
pwa_themecolor        : '#1e88e5'
pwa_backgroundcolor   : '#1e88e5'

serviceworker         : true
#google_analytics      : 'UA-134156954-1'
#disqus_name           : 'groveld'

# Custom Jekyll Configuration
title                 : 'Jekyll Theme'
tagline               : 'Minimalist Jekyll Theme'
description           : 'The Jekyll theme used for the personal website of Martin Groeneveld'
author                : 'Groveld'
email                 : 'groveld@pm.me'

phone                 : '+31610106931'
address               : 'Streetname 123<br>Zipcode City<br>Country'
legal                 : '<a href="/terms">Terms</a> &bull; <a href="/privacy">Privacy</a>'
